//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CNIcq.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CNICQ_DIALOG                102
#define IDS_STRING102                   102
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   129
#define IDC_DRAG                        130
#define IDC_FORBIDDEN                   131
#define IDC_HAND                        132
#define IDB_MAIN_BG                     137
#define IDB_SMALL_ICO                   138
#define IDB_BITMAP2                     139
#define IDB_BITMAP3                     140
#define IDB_BITMAP4                     143
#define IDD_CHAT_DIALOG                 144
#define IDR_CHAT_MENU                   145
#define IDR_POPUP_MENU                  146
#define IDB_EMOTIONS                    148
#define IDB_FORMATBAR                   153
#define IDB_FONTTYPE                    158
#define IDR_MENU_REPLY                  160
#define IDC_SHORTCUT_BTN1               1005
#define IDC_SHORTCUT_BTN2               1006
#define IDC_SHORTCUT_BTN3               1007
#define IDC_SHORTCUT_BTN4               1008
#define IDC_SHORTCUT_BTN5               1009
#define IDC_SHORTCUT_BTN6               1010
#define IDC_SHORTCUT_BTN7               1011
#define IDC_SHORTCUT_BTN8               1012
#define IDC_EDIT_SHOWMSG                1022
#define IDC_EDIT_SENDMSG                1023
#define IDC_BTN_CHAT_SEND               1024
#define IDC_TOOLWIN                     1025
#define IDC_EMOTONS                     1025
#define IDC_MESSAGE                     1026
#define IDC_BTN_FASTREPLY               1027
#define IDC_BTN_TOOLWIN                 1028
#define IDC_STATUSBAR                   32500
#define ID_FILE_SW_USER                 32771
#define ID_FILE_STATUS_ONLINE           32772
#define ID_FILE_STATUS_HIDE             32773
#define ID_FILE_STATUS_OFFLINE          32774
#define ID_FILE_LOGIN                   32775
#define ID_FILE_LOGOUT                  32776
#define ID_FILE_EXIT                    32777
#define ID_MENUITEM32778                32778
#define ID_MENUITEM32779                32779
#define ID_HELP_ABOUT                   32780
#define ID_MENUITEM32781                32781
#define ID_MENUITEM32782                32782
#define ID_MENUITEM32783                32783
#define ID_MENUITEM32785                32785
#define ID_MENUITEM32786                32786
#define ID_MENUITEM32787                32787
#define ID_MENUITEM32788                32788
#define ID_MENUITEM32789                32789
#define ID_MENUITEM32790                32790
#define ID_MENUITEM32791                32791
#define ID_MENUITEM32792                32792
#define ID_MENUITEM32793                32793
#define ID_MENUITEM32794                32794
#define ID_MENUITEM32795                32795
#define ID_MENUITEM32796                32796
#define ID_MENUITEM32797                32797
#define ID_MENUITEM32798                32798
#define ID_MENUITEM32799                32799
#define ID_MENUITEM32800                32800
#define ID_MENUITEM32801                32801
#define ID_MENUITEM32802                32802
#define ID_MENU_TOOLS_SHOWTAB           32802
#define ID_MENUITEM32803                32803
#define ID_MENUITEM32805                32805
#define ID_MENUITEM32806                32806
#define ID_MENUITEM32807                32807
#define ID_MENU_CHAT_EXIT               32808
#define ID_MENUITEM32809                32809
#define ID_MENUITEM32810                32810
#define ID_CHAR_BOLD                    32811
#define ID_CHAR_ITALIC                  32812
#define ID_CHAR_UNDERLINE               32813
#define ID_CHAR_COLOR                   32814
#define ID_CHAR_EMOTION                 32815
#define ID_MENUITEM32816                32816
#define ID_MENUITEM32817                32817
#define ID_MENUITEM32818                32818
#define ID_MENUITEM32819                32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
