//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by rtcsample.rc
//
#define IDD_DIALOG_LOGON                101
#define IDD_DIALOG_WATCHER              102
#define IDR_MENU1                       103
#define IDR_MENU_APP                    103
#define IDD_DIALOG_ADDRESS_NAME         104
#define IDD_DIALOG_ADDRESS              105
#define IDR_MENU_IM                     105
#define IDR_MENU_AV                     106
#define IDD_DIALOG_SESSION              106
#define IDR_MENU_BUDDY                  107
#define IDD_DIALOG_AUTH                 107
#define IDR_MENU_USER                   108
#define IDD_DIALOG_NAME                 108
#define IDR_MENU_WATCHERS               109
#define IDD_DIALOG_OPTIONS              109
#define IDR_MENU_WATCHER                110
#define ID_TOOLS_OPTIONS                110
#define IDR_MENU_GROUPS                 111
#define ID_Menu                         111
#define IDR_MENU_GROUP                  112
#define ID_BUDDY_PROPERTIES             112
#define IDD_DIALOG_DIALPAD              113
#define ID_TOOLS_DTMFDIALPAD            114
#define IDI_MINUS                       116
#define IDI_PLUS                        117
#define IDC_EDIT_LOGON_USERURI          1000
#define IDC_COMBO_LOGON_TRANSPORT       1001
#define IDC_EDIT_LOGON_SERVER           1002
#define IDC_BUTTON_WATCHER_ALLOW        1002
#define IDC_BUTTON_WATCHER_BLOCK        1003
#define IDC_CHECK_WATCHER_ADD_BUDDY     1004
#define IDC_STATIC_WATCHER_URI          1005
#define IDC_STATIC_WATCHER_NAME         1006
#define IDC_EDIT_ADDRESS_URI            1006
#define IDC_EDIT_ADDRESS_NAME           1007
#define IDC_STATIC_SESSION_NAME         1008
#define IDC_STATIC_SESSION_URI          1009
#define IDC_BUTTON_SESSION_ACCEPT       1010
#define IDC_BUTTON_SESSION_REJECT       1011
#define IDC_EDIT_AUTH_ACCOUNT           1012
#define IDC_EDIT_AUTH_USERURI           1013
#define IDC_EDIT_AUTH_PASSWORD          1014
#define IDC_EDIT_OPTIONS_NAME           1014
#define IDC_STATIC_AUTH_REALM           1015
#define IDC_EDIT_OPTIONS_NUM            1015
#define IDC_LIST1                       1016
#define IDC_STATIC_OPTIONS_NAME         1017
#define IDC_STATIC_OPTIONS_NUM          1018
#define IDC_CHECK_OPTIONS_APPBW         1019
#define IDC_EDIT_OPTIONS_APPBW          1020
#define IDC_RADIO_AVENC_OPTIONS_UNSUPP  1026
#define IDC_RADIO_AVENC_OPTIONS_SUPP    1027
#define IDC_RADIO_AVENC_OPTIONS_REQ     1028
#define IDC_RADIO_T120ENC_OPTIONS_UNSUPP 1029
#define IDC_BUTTON_DIALPAD_1            1029
#define IDC_RADIO_T120ENC_OPTIONS_SUPP  1030
#define IDC_BUTTON_DIALPAD_2            1030
#define IDC_RADIO_T120ENC_OPTIONS_REQ   1031
#define IDC_BUTTON_DIALPAD_3            1031
#define IDC_BUTTON_DIALPAD_4            1032
#define IDC_BUTTON_DIALPAD_5            1033
#define IDC_BUTTON_DIALPAD_6            1034
#define IDC_BUTTON_DIALPAD_7            1035
#define IDC_BUTTON_DIALPAD_8            1036
#define IDC_EDIT1                       1036
#define IDC_BUTTON_DIALPAD_9            1037
#define IDC_CHECK_OPTIONS_T120          1037
#define IDC_BUTTON_DIALPAD_0            1038
#define IDC_BUTTON_DIALPAD_STAR         1039
#define IDC_BUTTON_DIALPAD_HASH         1040
#define IDC_STATUSBAR                   2000
#define IDC_IM_DISPLAY                  2002
#define IDC_IM_EDIT                     2003
#define IDC_IM_SEND                     2004
#define IDC_MIC_VOL                     2005
#define IDC_MIC_MUTE                    2006
#define IDC_SPK_VOL                     2007
#define IDC_SPK_MUTE                    2008
#define IDC_IM_PARTLIST                 2009
#define IDC_US_FIRSTNAME                2010
#define IDC_US_SEARCH                   2011
#define IDC_US_RESULTLIST               2012
#define IDC_WATCHERLIST                 2013
#define IDC_GROUPLIST                   2014
#define IDC_BUDDYTREE                   2015
#define IDC_US_LASTNAME                 2016
#define IDC_US_FNLABEL                  2017
#define IDC_US_LNLABEL                  2018
#define IDC_US_EMAIL                    2019
#define IDC_US_MLABEL                   2019
#define ID_FILE_LOGON                   40001
#define ID_FILE_LOGOFF                  40002
#define ID_FILE_EXIT                    40003
#define ID_ACTION_ADDBUDDY              40004
#define ID_ACTION_CALL                  40005
#define ID_ACTION_MESSAGE               40006
#define ID_TOOLS_TUNINGWIZARD           40007
#define ID_BUDDY_CALL                   40008
#define ID_BUDDY_MESSAGE                40009
#define ID_BUDDY_REMOVE                 40010
#define ID_FILE_PRESENCESTATUS_OFFLINE  40011
#define ID_FILE_PRESENCESTATUS_ONLINE   40012
#define ID_FILE_PRESENCESTATUS_AWAY     40013
#define ID_FILE_PRESENCESTATUS_IDLE     40014
#define ID_FILE_PRESENCESTATUS_BUSY     40015
#define ID_FILE_PRESENCESTATUS_BERIGHTBACK 40016
#define ID_FILE_PRESENCESTATUS_ONTHEPHONE 40017
#define ID_FILE_PRESENCESTATUS_OUTTOLUNCH 40018
#define ID_ACTION_ADDPARTICIPANT        40019
#define ID_BUDDY_REFRESH                40020
#define ID_TOOLS_USERSEARCH             40021
#define ID_USER_CALL                    40022
#define ID_USER_MESSAGE                 40023
#define ID_USER_PHONE                   40024
#define ID_USER_ADDBUDDY                40025
#define ID_VIEW_VIDEO                   40026
#define ID_TOOLS_WATCHERS               40027
#define ID_ACTION_ADDWATCHER            40028
#define ID_WATCHER_ALLOW                40029
#define ID_WATCHER_BLOCK                40030
#define ID_WATCHER_DENY                 40031
#define ID_WATCHER_PROMPT               40032
#define ID_WATCHER_REMOVE               40033
#define ID_TOOLS_GROUPS                 40034
#define ID_ACTION_ADDGROUP              40035
#define ID_GROUP_REMOVE                 40036
#define ID_VIEW_APPSHARING              40037
#define ID_VIEW_WHITEBOARD              40038
#define ID_GROUP_BUDDY_ADD		40039
#define ID_GROUP_BUDDY_REMOVE		40040

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        118
#define _APS_NEXT_COMMAND_VALUE         40039
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
